export const BASE_URL_CATEGORY="http://localhost:3001/catalogs"
export const BASE_URL_PRODUCT="http://localhost:3001/products"
export const BASE_URL_COLOR="http://localhost:3001/colors"
export const BASE_URL_SIZE="http://localhost:3001/sizes"
export const BASE_URL_CART="http://localhost:3001/carts"
export const BASE_URL_PRODUCTDETAIL="http://localhost:3001/productDetails"
